import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");
const dataDir = path.join(root, "data");
const outFile = path.join(root, "src", "data.generated.js");

async function readJson(name) {
  const filePath = path.join(dataDir, name);
  const text = await readFile(filePath, "utf8");
  return JSON.parse(text);
}

function serializeExport(name, value) {
  return `export const ${name} = ${JSON.stringify(value, null, 2)};\n`;
}

async function main() {
  const snapshot = await readJson("snapshot.json");
  const hostedModels = await readJson("hosted-models.json");
  const localModels = await readJson("local-models.json");
  const topology = await readJson("topology.json");
  const roadmap = await readJson("roadmap.json");

  const fileContents = [
    "// This file is generated by scripts/generate-data.mjs",
    "// Edit JSON in /data and rerun `npm run generate:data`.\n",
    serializeExport("snapshot", snapshot),
    serializeExport("hostedModels", hostedModels),
    serializeExport("localModels", localModels),
    serializeExport("topology", topology),
    serializeExport("roadmap", roadmap),
  ].join("\n");

  await mkdir(path.dirname(outFile), { recursive: true });
  await writeFile(outFile, fileContents);
  process.stdout.write(`Wrote ${path.relative(root, outFile)}\n`);
}

main().catch((error) => {
  process.stderr.write(`${error.stack}\n`);
  process.exitCode = 1;
});
