export const snapshot = {
  asOf: "May 31, 2026",
  description:
    "Curated snapshot for agentic-framework planning. Pricing is sourced from official vendor pages; benchmark positioning and agent-fit values are blended editorial scores for the UI scaffold.",
  sources: [
    {
      label: "LM Arena reference board",
      url: "https://huggingface.co/spaces/lmarena-ai/arena-leaderboard",
    },
    {
      label: "OpenAI API pricing",
      url: "https://openai.com/api/pricing/",
    },
    {
      label: "Anthropic Claude pricing",
      url: "https://www.anthropic.com/pricing#api",
    },
    {
      label: "Google AI pricing",
      url: "https://ai.google.dev/gemini-api/docs/pricing",
    },
    {
      label: "xAI API docs",
      url: "https://docs.x.ai/docs/models",
    },
    {
      label: "Ollama model library",
      url: "https://ollama.com/library",
    },
  ],
};

export const hostedModels = [
  {
    id: "claude-sonnet-4",
    name: "Claude Sonnet 4",
    provider: "Anthropic",
    tier: "Flagship",
    arenaScore: 96,
    agentScore: 98,
    latency: 3.4,
    contextWindow: 200,
    inputCost: 3,
    outputCost: 15,
    cacheCost: 0.3,
    toolUse: "Excellent",
    modalities: ["text", "vision", "tool calling"],
    regions: ["us", "eu", "apac"],
    notes: "Balanced reasoning, strong tool loops, reliable structured output.",
  },
  {
    id: "gemini-25-pro",
    name: "Gemini 2.5 Pro",
    provider: "Google",
    tier: "Flagship",
    arenaScore: 97,
    agentScore: 96,
    latency: 4.1,
    contextWindow: 1000,
    inputCost: 2.5,
    outputCost: 15,
    cacheCost: 0.25,
    toolUse: "Excellent",
    modalities: ["text", "vision", "audio", "tool calling"],
    regions: ["us", "eu", "apac"],
    notes: "Massive context headroom, excellent for retrieval-heavy agent systems.",
  },
  {
    id: "gpt-41",
    name: "GPT-4.1",
    provider: "OpenAI",
    tier: "Flagship",
    arenaScore: 94,
    agentScore: 95,
    latency: 3.1,
    contextWindow: 128,
    inputCost: 2,
    outputCost: 8,
    cacheCost: 0.5,
    toolUse: "Excellent",
    modalities: ["text", "vision", "tool calling"],
    regions: ["us", "eu", "apac"],
    notes: "Fastest high-end planner in the set once cost is normalized.",
  },
  {
    id: "grok-4",
    name: "Grok 4",
    provider: "xAI",
    tier: "Flagship",
    arenaScore: 95,
    agentScore: 92,
    latency: 3.8,
    contextWindow: 256,
    inputCost: 3,
    outputCost: 15,
    cacheCost: 0.5,
    toolUse: "Strong",
    modalities: ["text", "vision"],
    regions: ["us", "eu"],
    notes: "Very competitive frontier model with a slightly narrower ops footprint.",
  },
  {
    id: "gemini-25-flash",
    name: "Gemini 2.5 Flash",
    provider: "Google",
    tier: "Efficiency",
    arenaScore: 87,
    agentScore: 90,
    latency: 1.3,
    contextWindow: 1000,
    inputCost: 0.35,
    outputCost: 1.2,
    cacheCost: 0.05,
    toolUse: "Strong",
    modalities: ["text", "vision", "audio", "tool calling"],
    regions: ["us", "eu", "apac"],
    notes: "Excellent evaluator or router model for high-volume loops.",
  },
  {
    id: "gpt-41-mini",
    name: "GPT-4.1 mini",
    provider: "OpenAI",
    tier: "Efficiency",
    arenaScore: 84,
    agentScore: 88,
    latency: 1.5,
    contextWindow: 128,
    inputCost: 0.4,
    outputCost: 1.6,
    cacheCost: 0.1,
    toolUse: "Strong",
    modalities: ["text", "vision", "tool calling"],
    regions: ["us", "eu", "apac"],
    notes: "Cheap enough for verification passes and memory compression jobs.",
  },
];

export const localModels = [
  {
    id: "qwen3-32b",
    name: "Qwen3 32B",
    family: "Qwen",
    fitScore: 93,
    arenaScore: 88,
    vramGb: 20.5,
    params: 32,
    quant: "Q4_K_M",
    contextWindow: 131,
    toolUse: "Strong",
    bestFor: "Balanced local planner",
    notes: "A strong default when you want local autonomy without giving up reasoning depth.",
  },
  {
    id: "gemma3-27b",
    name: "Gemma 3 27B",
    family: "Google",
    fitScore: 90,
    arenaScore: 85,
    vramGb: 17.2,
    params: 27,
    quant: "Q4_K_M",
    contextWindow: 128,
    toolUse: "Strong",
    bestFor: "Vision-aware local agents",
    notes: "Comfortable 4090 fit with room for a small sidecar service.",
  },
  {
    id: "mistral-small-24b",
    name: "Mistral Small 3 24B",
    family: "Mistral",
    fitScore: 89,
    arenaScore: 83,
    vramGb: 14.1,
    params: 24,
    quant: "Q4_K_M",
    contextWindow: 128,
    toolUse: "Strong",
    bestFor: "Low-latency local execution",
    notes: "A very practical model for browser or code subagents on a single GPU.",
  },
  {
    id: "llama-31-8b",
    name: "Llama 3.1 8B",
    family: "Meta",
    fitScore: 81,
    arenaScore: 74,
    vramGb: 5.3,
    params: 8,
    quant: "Q4_K_M",
    contextWindow: 128,
    toolUse: "Good",
    bestFor: "Cheap verifier or summarizer",
    notes: "Tiny footprint makes it a good sidecar for guardrails and retries.",
  },
  {
    id: "phi-4-mini",
    name: "Phi-4 mini",
    family: "Microsoft",
    fitScore: 76,
    arenaScore: 71,
    vramGb: 4.8,
    params: 7,
    quant: "Q4_K_M",
    contextWindow: 128,
    toolUse: "Good",
    bestFor: "Always-on local helpers",
    notes: "Ideal for light triage, tagging, and background automation loops.",
  },
];

export const topology = [
  {
    title: "Planner",
    blurb: "Frontier reasoning model handles task breakdown, tool choice, and recovery paths.",
    color: "rose",
  },
  {
    title: "Executor",
    blurb: "Fast API model runs browser, code, or retrieval substeps with lower token burn.",
    color: "gold",
  },
  {
    title: "Verifier",
    blurb: "A cheap reviewer checks outputs, flags regressions, and decides on retries.",
    color: "sky",
  },
  {
    title: "Local fallback",
    blurb: "A 4090-hosted model absorbs private or offline work without leaving the machine.",
    color: "mint",
  },
];

export const roadmap = [
  "Replace the curated snapshot with a scheduled ingestion job for leaderboard and pricing data.",
  "Add per-framework presets for OpenClaw, LangGraph, AutoGen, and CrewAI.",
  "Expose user-selectable workload mixes such as browser automation, code repair, or memory indexing.",
  "Publish a JSON schema so the board can be fed from GitHub Actions or Supabase later.",
];
